const sdData = [
    "task(e8nzydbzv41tzpa)",
    2,
    "photo of a nude woman, naked​",
    "((clothing), (monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), jeans, tattoo, wet, water, clothing, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy​",
    [],
    null,
    null,
    {
        "image": "",
        "mask": "",
    },
    null,
    null,
    null,
    null,
    20,
    "DPM++ SDE Karras",
    4,
    0,
    "fill",
    1,
    1,
    7,
    1.5,
    0.75,
    null,
    512,
    512,
    1,
    "Just resize",
    "Only masked",
    32,
    "Inpaint masked",
    "",
    "",
    "",
    [],
    false,
    [],
    "",
    "None",
    false,
    "",
    0.8,
    -1,
    false,
    -1,
    0,
    0,
    0,
    "* `CFG Scale` should be 2 or lower.",
    true,
    true,
    "",
    "",
    true,
    50,
    true,
    1,
    0,
    false,
    4,
    0.5,
    "Linear",
    "None",
    "<p style=\"margin-bottom:0.75em\">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>",
    128,
    8,
    [
        "left",
        "right",
        "up",
        "down"
    ],
    1,
    0.05,
    128,
    4,
    "fill",
    [
        "left",
        "right",
        "up",
        "down"
    ],
    false,
    false,
    "positive",
    "comma",
    0,
    false,
    false,
    "",
    "<p style=\"margin-bottom:0.75em\">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>",
    64,
    "None",
    2,
    "Seed",
    "",
    [],
    "Nothing",
    "",
    [],
    "Nothing",
    "",
    [],
    true,
    false,
    false,
    false,
    0,
    false,
    [],
    "{\"prompt\": \"photo of a nude woman, naked\\u200b\", \"all_prompts\": [\"photo of a nude woman, naked\\u200b\"], \"negative_prompt\": \"((clothing), (monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), jeans, tattoo, wet, water, clothing, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy\\u200b\", \"all_negative_prompts\": [\"((clothing), (monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), jeans, tattoo, wet, water, clothing, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy\\u200b\"], \"seed\": 8312706, \"all_seeds\": [8312706], \"subseed\": 3821194451, \"all_subseeds\": [3821194451], \"subseed_strength\": 0, \"width\": 512, \"height\": 512, \"sampler_name\": \"DPM++ SDE Karras\", \"cfg_scale\": 7, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_name\": \"mistoonAnime_v20Inpainting\", \"sd_model_hash\": \"c77c3c7c15\", \"sd_vae_name\": null, \"sd_vae_hash\": null, \"seed_resize_from_w\": -1, \"seed_resize_from_h\": -1, \"denoising_strength\": 0.75, \"extra_generation_params\": {\"Mask blur\": 4}, \"index_of_first_image\": 0, \"infotexts\": [\"photo of a nude woman, naked\\u200b\\nNegative prompt: ((clothing), (monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), jeans, tattoo, wet, water, clothing, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy\\u200b\\nSteps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 8312706, Size: 512x512, Model hash: c77c3c7c15, Model: mistoonAnime_v20Inpainting, Denoising strength: 0.75, Conditional mask weight: 1.0, Mask blur: 4, Version: 1.6.1\"], \"styles\": [], \"job_timestamp\": \"20231129222837\", \"clip_skip\": 1, \"is_using_inpainting_conditioning\": true}",
    "<p>photo of a nude woman, naked​<br>\nNegative prompt: ((clothing), (monochrome:1.3), (deformed, distorted, disfigured:1.3), (hair), jeans, tattoo, wet, water, clothing, shadow, 3d render, cartoon, ((blurry)), duplicate, ((duplicate body parts)), (disfigured), (poorly drawn), ((missing limbs)), logo, signature, text, words, low res, boring, artifacts, bad art, gross, ugly, poor quality, low quality, poorly drawn, bad anatomy, wrong anatomy​<br>\nSteps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 8312706, Size: 512x512, Model hash: c77c3c7c15, Model: mistoonAnime_v20Inpainting, Denoising strength: 0.75, Conditional mask weight: 1.0, Mask blur: 4, Version: 1.6.1</p>",
    "<p class='comments'></p><div class='performance'><p class='time'>Time taken: <wbr><span class='measurement'>1 min. 38.3 sec.</span></p><p class='vram'><abbr title='Active: peak amount of video memory used during generation (excluding cached data)'>A</abbr>: <span class='measurement'>1.40 GB</span>, <wbr><abbr title='Reserved: total amout of video memory allocated by the Torch library '>R</abbr>: <span class='measurement'>7.97 GB</span>, <wbr><abbr title='System: peak amout of video memory allocated by all running programs, out of total capacity'>Sys</abbr>: <span class='measurement'>8.0/7.96582 GB</span> (100.0%)</p></div>"
]

export default sdData